import { Game } from "@/app/types/Game";
import GameCard from "../GameCard";

export default function TrendingGames() {
  const trendingGames: Game[] = [
    {
      id: 1,
      title: "The Last of Us Part 1",
      imageUrl: "/covers/the-last-of-us.jpg",
      releaseDate: "May 20, 2026",
      myscore: 10,
      metascore: 95,
      topPick: true,
      added: true,
      bookmarked: true,
      favorite: true,
      link: "#",
      platforms: [
        { name: "Windows", icon: "/icons/windows.svg" },
        { name: "PlayStation", icon: "/icons/playstation.svg" },
      ],
    },
    {
      id: 2,
      title: "Resident Evil 4",
      imageUrl: "/covers/resident-evil-4.jpg",
      releaseDate: "August 28, 2025",
      myscore: 9,
      metascore: 93,
      topPick: true,
      added: true,
      bookmarked: true,
      favorite: true,
      link: "#",
      platforms: [
        { name: "Windows", icon: "/icons/windows.svg" },
        { name: "PlayStation", icon: "/icons/playstation.svg" },
        { name: "Xbox", icon: "/icons/xbox.svg" },
      ],
    },
    {
      id: 3,
      title: "Returnal",
      imageUrl: "/covers/returnal.jpg",
      releaseDate: "September 21, 2025",
      myscore: null,
      metascore: 86,
      topPick: false,
      added: false,
      bookmarked: false,
      favorite: false,
      link: "#",
      platforms: [
        { name: "Windows", icon: "/icons/windows.svg" },
        { name: "PlayStation", icon: "/icons/playstation.svg" },
      ],
    },
    {
      id: 4,
      title: "Hogwarts Legacy",
      imageUrl: "/covers/hogwarts-legacy.jpg",
      releaseDate: "June 26, 2025",
      myscore: null,
      metascore: 84,
      topPick: false,
      added: false,
      bookmarked: false,
      favorite: false,
      link: "#",
      platforms: [
        { name: "Windows", icon: "/icons/windows.svg" },
        { name: "PlayStation", icon: "/icons/playstation.svg" },
        { name: "Xbox", icon: "/icons/xbox.svg" },
        { name: "Nintendo", icon: "/icons/nintendo.svg" },
      ],
    },
    {
      id: 5,
      title: "Need For Speed The Run",
      imageUrl: "/covers/need-for-speed-the-run.jpg",
      releaseDate: "March 27, 2016",
      myscore: 8,
      metascore: 68,
      topPick: true,
      added: false,
      bookmarked: false,
      favorite: true,
      link: "#",
      platforms: [
        { name: "Windows", icon: "/icons/windows.svg" },
        { name: "PlayStation", icon: "/icons/playstation.svg" },
        { name: "Xbox", icon: "/icons/xbox.svg" },
        { name: "Nintendo", icon: "/icons/nintendo.svg" },
      ],
    },
    {
      id: 6,
      title: "It Takes Two",
      imageUrl: "/covers/it-takes-two.jpg",
      releaseDate: "September 12, 2025",
      myscore: 9,
      metascore: 88,
      topPick: true,
      added: true,
      bookmarked: true,
      favorite: true,
      link: "#",
      platforms: [
        { name: "Windows", icon: "/icons/windows.svg" },
        { name: "PlayStation", icon: "/icons/playstation.svg" },
        { name: "Xbox", icon: "/icons/xbox.svg" },
        { name: "Nintendo", icon: "/icons/nintendo.svg" },
      ],
    },
    {
      id: 7,
      title: "Call of Duty: Modern Warfare 3",
      imageUrl: "/covers/call-of-duty-mw-3.jpg",
      releaseDate: "Aug 8, 2020",
      myscore: 7,
      metascore: 88,
      topPick: false,
      added: true,
      bookmarked: false,
      favorite: false,
      link: "#",
      platforms: [
        { name: "Windows", icon: "/icons/windows.svg" },
        { name: "PlayStation", icon: "/icons/playstation.svg" },
        { name: "Xbox", icon: "/icons/xbox.svg" },
        { name: "Nintendo", icon: "/icons/nintendo.svg" },
      ],
    },
    {
      id: 8,
      title: "Metal Gear Solid 3",
      imageUrl: "/covers/metal-gear-solid-3.jpg",
      releaseDate: "Oct 2, 2007",
      myscore: null,
      metascore: 91,
      topPick: false,
      added: true,
      bookmarked: false,
      favorite: false,
      link: "#",
      platforms: [
        { name: "Windows", icon: "/icons/windows.svg" },
        { name: "PlayStation", icon: "/icons/playstation.svg" },
        { name: "Xbox", icon: "/icons/xbox.svg" },
        { name: "Nintendo", icon: "/icons/nintendo.svg" },
      ],
    },
  ];
  return (
    <div className="grid grid-cols-2 gap-x-2 gap-y-4 sm:grid-cols-3 sm:gap-x-3 lg:grid-cols-4 xl:gap-x-4 xl:gap-y-5 2xl:grid-cols-5 2xl:gap-x-3">
      {trendingGames.map((game) => (
        <GameCard key={game.id} game={game} />
      ))}
    </div>
  );
}
